In [ ]:
# simple mouse capture demo. Note video doesn't play. We only show the first image of the video
#click leftmouse and right mouse button on video window and verify output in output window

#apple trackpad 1 finger left mouse button
# 2 fingers right mouse button. How is that intuitive? 

import cv2
import numpy as np


def mouse_capture(event, x, y, flags, param):
    if event==cv2.EVENT_LBUTTONDOWN:
        print 'left mouse button'
    elif event==cv2.EVENT_RBUTTONDOWN:
        print 'right mouse button'
    

vc = cv2.VideoCapture('/Users/dc/videodemos/video_mouse.mov')

ret_code, first_frame = vc.read()

cv2.namedWindow('show_firstFrame')
cv2.setMouseCallback('show_firstFrame', mouse_capture)

print first_frame
while True:
    cv2.imshow('show_firstFrame', first_frame)
    waitKey = cv2.waitKey(10000) & 0xFF
    if waitKey == ord('q'):
        break

cv2.destroyAllWindows()
cv2.waitKey(1)
cv2.waitKey(1)
cv2.waitKey(1)

print 'done'



[[[ 23  38  33]
  [ 24  39  35]
  [ 28  43  38]
  ..., 
  [125 133 132]
  [141 148 147]
  [148 155 154]]

 [[ 15  30  25]
  [ 17  32  28]
  [ 21  36  31]
  ..., 
  [ 98 105 104]
  [106 113 112]
  [109 117 115]]

 [[ 11  27  22]
  [ 12  28  23]
  [ 18  34  29]
  ..., 
  [ 63  70  69]
  [ 66  73  72]
  [ 69  76  75]]

 ..., 
 [[132 133 137]
  [132 133 137]
  [132 133 137]
  ..., 
  [ 76  74  75]
  [ 85  85  85]
  [ 91  91  91]]

 [[132 133 137]
  [132 133 137]
  [132 133 137]
  ..., 
  [ 79  78  78]
  [ 76  76  76]
  [ 76  76  76]]

 [[132 133 137]
  [132 133 137]
  [132 133 137]
  ..., 
  [ 79  78  78]
  [ 76  76  76]
  [ 76  76  76]]]
left mouse button
left mouse button
left mouse button
left mouse button
left mouse button
left mouse button
left mouse button
right mouse button
right mouse button
left mouse button
left mouse button
left mouse button
left mouse button
left mouse button
left mouse button
