In [1]:
#store each frame as a jpg and txt. The txt files take less space!

# the cv2.waitKey(10000) keeps the image there for 10 seconds, if this doesn't work 
# then you have to add cv2.waitKey(1) to other sections to get this to work before detectiong the 
# key press
# keyboard q to kill the image display before timeout
# the codec/file extensions arent well documented
# fourcc if mp4v you need video_writer to have file name m4v extension
# fourcc if mjpg you need video_writer to have file name avi extension
# else you get no output

# for images you can use jpg extension. Does conversion for you. Frame as 2d numpy array works

import cv2
import numpy as np
import os
import matplotlib.pyplot as plt

def grayscale(img):
    return cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
    
    
def canny(img):
    #compute median of pixels, use this to set low/high threshold?
    median = np.median(img)
    sigma = 0.33
    lower = int(max(0,(1.-sigma)*median))
    upper = int(min(0,(1.+sigma)*median))
    
    return cv2.Canny(img, lower, upper)
    
    
def gaussian_blur(img):
     return cv2.GaussianBlur(img, (3, 3), 0)
    
def hough(img):
    
    
    
    
vc = cv2.VideoCapture("/Users/dc/videodemos/video_mouse.mov")
print '---------properties---------------'
#print vc.get(cv2.cv.CV_CAP_PROP_FRAME_COUNT)
print '----------------------------------'

#fourcc = cv2.cv.CV_FOURCC('m', 'p', '4', 'v') #mv4 extension
fourcc = cv2.cv.CV_FOURCC('M','J','P','G') #avi extenxion
#changing frame rate from 30 to 20 gets this to write. Have no idea what the original frame rate is. 
video_writer = cv2.VideoWriter("/Users/dc/videodemos/video_js/frame_dir/output.avi",fourcc, 20.0, (500,281),True)
cv2.namedWindow('image', cv2.WINDOW_NORMAL)
try:
    os.stat("/Users/dc/videodemos/video_js/frame_dir")
except:
    os.mkdir("/Users/dc/videodemos/video_js/frame_dir")

num=0
while True:
    ret_code,frame = vc.read()
    print frame.shape
    if ret_code:
        print "writing frame", frame
        cv2.imshow("image",frame)
        
        grey_scale = 
        canny = 
        hough = 
        
        video_writer.write(frame)
        #cv2.waitKey(10000) # for 1 image
        cv2.waitKey(1) # for video stream
        key = cv2.waitKey(1) & 0XFF
        if key == ord('q'):
            break
        print str(num)
        f = open("/Users/dc/videodemos/video_js/frame_dir/"+str(num)+'.txt', 'w')
        f.write(str(frame))
        try:
            result = cv2.imwrite("/Users/dc/videodemos/video_js/frame_dir/"+str(num)+".jpg",frame)
            print "result:", result
        except:
            print "bad write"
        f.close()
        num +=1
        #break
        
#cv2.waitKey(1) not needed webposts wrong
#cv2.waitKey(1) not needed webposts wrong
#cv2.waitKey(1) not needed webposts wrong
vc.release()
video_writer.release()
cv2.destroyAllWindows()
cv2.waitKey(1)
cv2.waitKey(1)
print "done"

/Users/dc/venv/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')


---------properties---------------
----------------------------------
(281, 500, 3)
writing frame [[[ 23  38  33]
  [ 24  39  35]
  [ 28  43  38]
  ..., 
  [125 133 132]
  [141 148 147]
  [148 155 154]]

 [[ 15  30  25]
  [ 17  32  28]
  [ 21  36  31]
  ..., 
  [ 98 105 104]
  [106 113 112]
  [109 117 115]]

 [[ 11  27  22]
  [ 12  28  23]
  [ 18  34  29]
  ..., 
  [ 63  70  69]
  [ 66  73  72]
  [ 69  76  75]]

 ..., 
 [[132 133 137]
  [132 133 137]
  [132 133 137]
  ..., 
  [ 76  74  75]
  [ 85  85  85]
  [ 91  91  91]]

 [[132 133 137]
  [132 133 137]
  [132 133 137]
  ..., 
  [ 79  78  78]
  [ 76  76  76]
  [ 76  76  76]]

 [[132 133 137]
  [132 133 137]
  [132 133 137]
  ..., 
  [ 79  78  78]
  [ 76  76  76]
  [ 76  76  76]]]
0
result: True
(281, 500, 3)
writing frame [[[ 23  38  33]
  [ 24  39  35]
  [ 28  43  38]
  ..., 
  [125 133 132]
  [141 148 147]
  [148 155 154]]

 [[ 15  30  25]
  [ 17  32  28]
  [ 21  36  31]
  ..., 
  [ 98 105 104]
  [106 113 112]
  [109 117 115]]

 [[ 

AttributeError: 'NoneType' object has no attribute 'shape'